Conditionalize a couple of warning flags.

diff --git a/script/ghci-flags b/script/ghci-flags
--- a/script/ghci-flags
+++ b/script/ghci-flags
@@ -66,8 +66,8 @@ function flags {
   echo "-Wno-name-shadowing"
   echo "-Wno-safe"
   echo "-Wno-unsafe"
-  echo "-Wno-star-is-type"
-  echo "-Wno-missing-deriving-strategies"
+  [[ "$ghc_version" = 8.6.* ]] && echo "-Wno-star-is-type" || true
+  [[ "$ghc_version" = 8.8.* ]] && echo "-Wno-missing-deriving-strategies" || true
 }
 
 flags > "$output_file"
